name: Release
description: "Release a new version"
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Released
        run: |
          echo "Released"
